### PR TITLE
fix(sql): handle commit/rollback error when tracing transcation

### LINKED ISSUE #38: Rollback error after mysql database transaction Commit
code：
```
tx := db.BeginTx(ctx, &sql.TxOptions{})
defer tx.Rollback()
...
 tx.Commit()
```

output：
```
panic: send on closed channel

goroutine 281 [running]:
github.com/SkyAPM/go2sky.(*rootSegmentSpan).End.func1(0xc0006167b0)
       vendor/github.com/SkyAPM/go2sky/segment.go:209 +0x4e
created by github.com/SkyAPM/go2sky.(*rootSegmentSpan).End
        vendor/github.com/SkyAPM/go2sky/segment.go:208 +0x85
exit status 2
```

### PR DESCRIPTION
**Pull request by kagaya85**
Now, sql plugin will close a span when commit/rollback returns error, it may call `span.End()` repeatly and cause a panic, we want return the `database/sql` errors to the upper instead of get a panic. 

Add defer function to handle the return error and will not call `span.End()` when error is not nil

fix #38

### CODE REVIEW

**Comment by kagaya85** [comment]
How about add the error message to the span and close it even the `commit` failed, to avoid unexpected panic, this may need add a method like `span.IsEnd()` to check if the  transcation span is closed. If we don't call `span.End()` when `commit` failed, the previous related span in this transcation period may not be reported.

**Comment by wu-sheng** [comment]
> Now, sql plugin will close a span when commit/rollback returns error, it may call span.End() repeatly and cause a panic, we want return the database/sql errors to the upper instead of get a panic.
Add defer function to handle the return error and will not call span.End() when error is not nil

I think we should consider separating the span, because as you mentioned in the codes, if there is connection leak(commit error, but no rollback called) or rollback fails, the span wouldn't be closed as expected, which is unexpected.

The tracing system is designed to tell the truth, rather than not working as well as original codes. 

You could check the SkyWalking Java agent's JDBC plugin, commit and rollback have there own spans, then no panic and always presents the complete trace.

File: sql/tx.go [hunk 1]
```diff
@@ -33,20 +33,32 @@ type Tx struct {
...
+			}
+			tx.span.End()
+		}()
 	}
 	return tx.Tx.Commit()
 }
 
-// Rollback support trace
-func (tx *Tx) Rollback() error {
+// Rollback support trace, span will not End when tx.Rollback returns error
```
Comment (wu-sheng) [inline sql/tx.go:51]: Span doesn't ending is pretty dangerous and hard to understand.

**Review by wu-sheng — DISMISSED** [review]
LGTM, wait for @arugal

**Comment by kagaya85** [comment]
Please hold this PR, we consider using separate `Begin/Commit/Rollback` span instead of the `Tx` span, in addition, there are two considerations may need to discuss:

* After using the separate span, the trace will not show the entire execution process for each transcation directly, for example, understanding one transcation cost time will become difficult
* Span validity check is also needed in this PR, even in septarate tx span, we need to ensure the parent span is still valid when start a new span to avoid panic, I can improve this in another PR

**Comment by wu-sheng** [comment]
> After using the separate span, the trace will not show the entire execution process for each transcation directly, for example, understanding one transcation cost time will become difficult

You could calculate the whole time by using tag or log in the span, such as commit or rollback. Also, the backend provides the logic endpoint concept(logic name + duration in tags) for you to measure things like this.

> Span validity check is also needed in this PR, even in septarate tx span, we need to ensure the parent span is still valid when start a new span to avoid panic, I can improve this in another PR

You could make the choice whether in this PR or through another one.

File: sql/go.mod [hunk 2]
```diff
@@ -7,9 +7,10 @@ require (
...
 	github.com/google/uuid v1.3.0 // indirect
 	github.com/pkg/errors v0.9.1 // indirect
-	golang.org/x/net v0.0.0-20210805182204-aaa1db679c0d // indirect
-	golang.org/x/sys v0.0.0-20210806184541-e5e7981a1069 // indirect
-	google.golang.org/genproto v0.0.0-20210805201207-89edb61ffb67 // indirect
-	google.golang.org/grpc v1.39.1 // indirect
-	skywalking.apache.org/repo/goapi v0.0.0-20210804062511-c324007aab53
+	golang.org/x/net v0.0.0-20211216030914-fe4d6282115f // indirect
+	golang.org/x/sys v0.0.0-20211216021012-1d35b9e2eb4e // indirect
+	golang.org/x/text v0.3.7 // indirect
```
Comment (wu-sheng) [inline sql/go.mod:12]: Is this expected?

File: sql/common.go [hunk 3]
```diff
@@ -59,21 +59,6 @@ func createSpan(ctx context.Context, tracer *go2sky.Tracer, opts *options, opera
 	return s, nil
 }
 
-func createLocalSpan(ctx context.Context, tracer *go2sky.Tracer, opts *options, operation string) (go2sky.Span, context.Context, error) {
```
Comment (wu-sheng) [inline sql/common.go:62]: No local span? Why it was there before?

Comment (kagaya85) [reply sql/common.go:62]: this because we treat a transcation span as a local span before, each operation in transcation is the child span of this local span, now it is not needed

Comment (wu-sheng) [reply sql/common.go:62]: Got it.

**Review by wu-sheng — APPROVED** [review]
